barowoori/foodpin-backend

Dockerfile
=> :sparkles: Dockerfile created

.github/workflows/ci.yml
=> :construction_worker: ci workflow on condition updated.

.github/workflows/cd.yml
> #6 
> ECR_URI, PROFILE, SERVICE 전역 변수 선언 및 초기화(setup-env) 완료
=> 🔨 cd workflow changed.

build.gradle, src/main/java/com/barowoori/foodpinbackend/config/doc/SwaggerConfig.java
=> :sparkles: Swagger setting

build.gradle, src/main/java/com/barowoori/foodpinbackend/common/exception/CustomException.java, src/main/java/com/barowoori/foodpinbackend/common/exception/ErrorCode.java, src/main/java/com/barowoori/foodpinbackend/common/exception/ErrorResponse.java, src/main/java/com/barowoori/foodpinbackend/common/exception/GlobalExceptionHandler.java, src/main/java/com/barowoori/foodpinbackend/config/aws/S3Config.java, src/main/java/com/barowoori/foodpinbackend/config/factory/YamlPropertySourceFactory.java, src/main/java/com/barowoori/foodpinbackend/member/command/domain/exception/MemberErrorCode.java, src/main/java/com/barowoori/foodpinbackend/member/command/domain/model/Member.java, src/main/java/com/barowoori/foodpinbackend/member/command/domain/service/GenerateNicknameService.java, src/main/java/com/barowoori/foodpinbackend/member/command/domain/service/ImageManager.java, src/main/java/com/barowoori/foodpinbackend/member/infra/domain/ImageDirectory.java, src/main/java/com/barowoori/foodpinbackend/member/infra/domain/S3ImageManager.java, src/test/java/com/barowoori/foodpinbackend/member/domain/MemberTests.java, src/test/java/com/barowoori/foodpinbackend/member/domain/service/GenerateNicknameServiceTests.java, src/test/java/com/barowoori/foodpinbackend/member/infra/domain/S3ImageManagerTests.java
> ex) #13 
> s3 config 설정, 파일 업로드, 삭제 기능 추가
>
=> :sparkles: s3 설정 및 업로드, 삭제 기능 추가

src/main/java/com/barowoori/foodpinbackend/member/command/domain/model/Member.java
> ex) #10 
> 코드 오타 및 컬럼 길이 수정
>
=> Feat 10 member entity creating

src/main/java/com/barowoori/foodpinbackend/document/command/domain/model/BusinessRegistration.java, src/main/java/com/barowoori/foodpinbackend/document/command/domain/model/DocumentType.java, src/main/java/com/barowoori/foodpinbackend/document/command/domain/repository/BusinessRegistrationRepository.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventDocument.java, src/main/java/com/barowoori/foodpinbackend/file/command/domain/model/File.java, src/main/java/com/barowoori/foodpinbackend/file/command/domain/service/ImageManager.java, src/main/java/com/barowoori/foodpinbackend/file/infra/domain/ImageDirectory.java, src/main/java/com/barowoori/foodpinbackend/file/infra/domain/S3ImageManager.java, src/main/java/com/barowoori/foodpinbackend/region/command/domain/model/Region.java, src/main/java/com/barowoori/foodpinbackend/region/command/domain/model/RegionGu.java, src/main/java/com/barowoori/foodpinbackend/region/command/domain/model/RegionGun.java, src/main/java/com/barowoori/foodpinbackend/truck/command/application/dto/RequestTruck.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/model/Truck.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/model/TruckDocument.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/dto/TruckDetail.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/dto/TruckDocumentManager.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/querydsl/TruckDocumentRepositoryCustom.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/querydsl/TruckDocumentRepositoryCustomImpl.java, src/test/java/com/barowoori/foodpinbackend/file/domain/S3ImageManagerTests.java, src/test/java/com/barowoori/foodpinbackend/truck/domain/repository/TruckDocumentRepositoryTests.java, src/test/java/com/barowoori/foodpinbackend/truck/query/TruckDetailServiceTests.java
> ex) #28 
> 푸드트럭 수정 관련 메서드 추가
>
=> Feat 28 event entity creating

src/main/java/com/barowoori/foodpinbackend/region/command/domain/model/RegionType.java, src/main/java/com/barowoori/foodpinbackend/region/command/domain/repository/dto/RegionCode.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/dto/TruckDetail.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/querydsl/TruckRegionRepositoryCustom.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/querydsl/TruckRegionRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/truck/query/application/TruckDetailService.java
> ex) #28 
> 트럭 상세 조회 시 지역코드 추가
>
=> :bug: truck detail api updated

src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/Event.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventNotice.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventRecruitDetail.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventRegion.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/EventNoticeRepository.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventNoticeRepositoryCustom.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventNoticeRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventRepositoryCustomImpl.java, src/test/java/com/barowoori/foodpinbackend/event/domain/repository/EventNoticeRepositoryTests.java, src/test/java/com/barowoori/foodpinbackend/event/query/EventDetailServiceTests.java, src/test/java/com/barowoori/foodpinbackend/event/query/EventListServiceTests.java
> ex) #28 
> 행사 지역 다중에서 단일로 변경, 행사 모집 시작일 삭제
>
=> :bug: event entity updated

src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventNotice.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventNoticeView.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventTruck.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/EventDocumentRepository.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/EventApplicableTruckList.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventNoticeRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/query/application/EventApplicableTruckListService.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/model/Truck.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/querydsl/TruckRepositoryCustom.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/querydsl/TruckRepositoryCustomImpl.java, src/test/java/com/barowoori/foodpinbackend/event/domain/repository/EventNoticeRepositoryTests.java, src/test/java/com/barowoori/foodpinbackend/event/query/EventApplicationTruckListServiceTests.java, src/test/java/com/barowoori/foodpinbackend/event/query/EventDetailServiceTests.java, src/test/java/com/barowoori/foodpinbackend/event/query/EventListServiceTests.java
> ex) #28
> event applicable truck list dao created
>
=> event applicable truck list dao created

src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventApplication.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventApplicationDate.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventApplicationStatus.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventTruck.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventTruckDate.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventTruckStatus.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/EventApplicationDateRepository.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/EventApplicationRepository.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/EventTruckDateRepository.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/EventTruckRepository.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/EventApplicationList.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventApplicationRepositoryCustom.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventApplicationRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventTruckRepositoryCustom.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventTruckRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/query/application/EventApplicationListService.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/model/Truck.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/querydsl/TruckRepositoryCustomImpl.java, src/test/java/com/barowoori/foodpinbackend/event/query/EventApplicationListServiceTests.java
> ex) #28
> 지원자 대기 목록
> 지원자 선정 목록
선정시 필터로 선택할 수 있는 상태 값(status) : ALL(전체), PENDING(답변대기중), CONFIRMED(참석확정), REJECTED(참석불가)
> 지원자 탈락 목록
>
=> :sparkles: 지원자 목록 관련 dao 생성

src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/Event.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/controller/EventController.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/querydsl/TruckRepositoryCustomImpl.java
> ex) #40
> 진행중인 행사 목록 조회 API 생성
> 지난 행사 목록 조회 API 생성
>
=> :sparkles: truck event manage list api created

src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/EventApplicationList.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/EventList.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/TruckEventApplicationList.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventApplicationRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/query/application/TruckEventApplicationListService.java
=> :sparkles: truck event application list dao created

src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/EventApplicationList.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventApplicationRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/controller/EventController.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/querydsl/TruckRepositoryCustomImpl.java
> ex) #50 
> 지원자 대기 목록 조회 생성
지원자 선정 목록 조회 생성
지원자 탈락 목록 조회 api 생성
>
=> :sparkles:  event application list api created

src/main/java/com/barowoori/foodpinbackend/region/command/domain/repository/querydsl/RegionRepositoryCustomImpl.java
=> :sparkles:  region code updated

src/main/java/com/barowoori/foodpinbackend/document/command/domain/model/DocumentType.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/model/TruckDocument.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/model/TruckDocumentPhoto.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/TruckDocumentPhotoRepository.java
> ex) #50
> 트럭 서류 타입 추가
트럭 서류 이미지 테이블 생성
>
=> :sparkles:  TruckDocument entity created

src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/EventList.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/TruckEventApplicationList.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventApplicationRepositoryCustom.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventApplicationRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/controller/EventController.java, src/main/java/com/barowoori/foodpinbackend/event/query/application/TruckEventApplicationListService.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/dto/TruckDetail.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/dto/TruckDocumentManager.java, src/main/java/com/barowoori/foodpinbackend/truck/query/application/TruckDetailService.java
> ex) #50
> 트럭 상세 조회 시 서류 정보 추가
트럭 지원한 행사 목록 조회 api 생성
>
=> Feat 50 event application api create

src/main/java/com/barowoori/foodpinbackend/truck/command/application/dto/ResponseTruck.java, src/main/java/com/barowoori/foodpinbackend/truck/command/application/service/TruckService.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/service/TruckManagerInvitationGenerator.java, src/main/java/com/barowoori/foodpinbackend/truck/controller/TruckController.java
> ex) #50
> 트럭 운영자 초대 문구 조회 api 
>
=> :sparkles:  truck manager invite message api created

src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/EventDetail.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/dto/TruckDetail.java
=> :sparkles:  photo dto id updated

src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/EventApplicationList.java
> ex) #50
> 지원자 대기 목록 dto에 evenDateId 추가
>
=> :sparkles:  event pending application list api dto updated

src/main/java/com/barowoori/foodpinbackend/event/command/application/dto/RequestEvent.java, src/main/java/com/barowoori/foodpinbackend/event/command/application/service/EventService.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventRecruitDetail.java
=> :sparkles:  event create api updated

src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/EventProposalRepository.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/AvailableEventListForProposal.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventProposalRepositoryCustom.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventProposalRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventRepositoryCustom.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/query/application/AvailableEventListForProposalService.java
> ex) #76 
> 제안할 행사 목록 조회 쿼리 생성
>
=> :sparkles: event proposal list query created

src/main/java/com/barowoori/foodpinbackend/common/exception/GlobalExceptionHandler.java, src/main/java/com/barowoori/foodpinbackend/config/logging/RestControllerLoggingAspect.java
=> ✨ API Logger, exception logger created.

src/main/java/com/barowoori/foodpinbackend/pushAlarmHistory/command/domain/model/PushAlarmHistory.java, src/main/java/com/barowoori/foodpinbackend/pushAlarmHistory/command/domain/repository/PushAlarmHistoryRepository.java
=> :sparkles: PushAlarmHistory entity created

src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/EventApplicableTruckList.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventApplicationRepositoryCustom.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventApplicationRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/query/application/EventApplicableTruckListService.java, src/main/java/com/barowoori/foodpinbackend/file/command/domain/service/ImageManager.java, src/main/java/com/barowoori/foodpinbackend/file/infra/domain/S3ImageManager.java, src/test/java/com/barowoori/foodpinbackend/event/query/EventListServiceTests.java
=> :sparkles: event list api fixed

src/main/java/com/barowoori/foodpinbackend/truck/command/application/service/TruckService.java
=> ✨ Truck delete manager api fixed.

src/main/java/com/barowoori/foodpinbackend/document/command/application/service/DocumentEmailService.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/controller/EventController.java, src/main/java/com/barowoori/foodpinbackend/file/command/domain/model/File.java, src/main/java/com/barowoori/foodpinbackend/file/command/domain/service/MailService.java, src/main/java/com/barowoori/foodpinbackend/file/infra/domain/S3ImageManager.java, src/main/java/com/barowoori/foodpinbackend/truck/command/application/dto/ResponseTruck.java, src/main/java/com/barowoori/foodpinbackend/truck/command/application/service/TruckService.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/querydsl/TruckDocumentRepositoryCustom.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/querydsl/TruckDocumentRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/truck/controller/TruckController.java, src/test/java/com/barowoori/foodpinbackend/file/domain/S3ImageManagerTests.java
> ex) #87
> s3 파일 업로드 시 uuid 제외
서류 파일명 조회 api 구현
이메일 템플릿 적용
>
=> Feat 87 email sender create

src/main/java/com/barowoori/foodpinbackend/config/security/SecurityConfig.java, src/main/resources/static/index.html, src/main/resources/static/script.js
=> :sparkles: index.html added

src/main/java/com/barowoori/foodpinbackend/event/command/application/service/EventService.java, src/main/java/com/barowoori/foodpinbackend/member/command/application/service/MemberService.java, src/main/java/com/barowoori/foodpinbackend/member/command/domain/model/Member.java, src/main/java/com/barowoori/foodpinbackend/member/controller/MemberController.java, src/main/java/com/barowoori/foodpinbackend/truck/command/application/service/TruckService.java
> #73 
> fcm 토큰 설정 api 추가
> 회원탈퇴 삭제 로직 수정
=> ✨ fcm token set api created, member delete logic refactored.

src/main/java/com/barowoori/foodpinbackend/member/command/application/service/MemberService.java
> #73 
> 로그아웃 로직 변경 - fcm 토큰 삭제
=> ✨ member logout logic changed.

src/main/java/com/barowoori/foodpinbackend/event/command/application/service/EventService.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/EventTruckRepository.java, src/main/java/com/barowoori/foodpinbackend/event/controller/EventController.java, src/main/java/com/barowoori/foodpinbackend/member/command/application/service/MemberService.java, src/main/java/com/barowoori/foodpinbackend/member/controller/MemberController.java, src/main/java/com/barowoori/foodpinbackend/truck/command/application/service/TruckService.java, src/main/java/com/barowoori/foodpinbackend/truck/controller/TruckController.java
=> ✨ member delete logic changed.

src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/EventDetail.java
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> :sparkles: event detail api fixed

src/main/java/com/barowoori/foodpinbackend/event/command/application/service/EventManagementService.java, src/main/java/com/barowoori/foodpinbackend/event/controller/EventManagementController.java
> #73 
> eventTruckId 사용하도록 변경
=> ✨ cancelEventSelection changed to use eventTruckId.

src/main/java/com/barowoori/foodpinbackend/notification/command/application/service/EventNotificationEventHandler.java, src/main/java/com/barowoori/foodpinbackend/notification/command/application/service/TruckNotificationEventHandler.java, src/main/java/com/barowoori/foodpinbackend/notification/infra/domain/FCMNotificationService.java
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> :sparkles: pushAlarm title updated

src/main/java/com/barowoori/foodpinbackend/event/command/application/service/EventStatusUpdater.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventRepositoryCustom.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventRepositoryCustomImpl.java
=> ✨ eventTruck, eventApplication reject logic refactored.

src/main/java/com/barowoori/foodpinbackend/event/command/application/service/EventStatusUpdater.java
=> ✨ Scheduler time setting changed.

src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventRecruitDetail.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventTruck.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/EventAppliedTruckDetail.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/EventDetail.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/EventSelectedTruckDetail.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/MemberForEventTruckFcmInfoDto.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/TruckEventApplicationList.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventTruckRepositoryCustom.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/querydsl/EventTruckRepositoryCustomImpl.java, src/main/java/com/barowoori/foodpinbackend/event/controller/EventController.java, src/main/java/com/barowoori/foodpinbackend/event/query/application/EventAppliedTruckDetailService.java, src/main/java/com/barowoori/foodpinbackend/event/query/application/EventTruckDetailService.java, src/main/java/com/barowoori/foodpinbackend/notification/command/application/service/EventNotificationEventHandler.java, src/main/java/com/barowoori/foodpinbackend/truck/command/domain/repository/dto/TruckDetail.java
> ex) #87
> 회신 알림 targetId 변경
지원한 행사 트럭 상세 보기 api
선정된 행사 트럭 상세 보기 api 
>
=> :sparkles: push alarm targetId updated

src/main/java/com/barowoori/foodpinbackend/document/command/application/dto/RequestDocument.java, src/main/java/com/barowoori/foodpinbackend/event/command/application/dto/RequestEvent.java, src/main/java/com/barowoori/foodpinbackend/event/command/application/service/EventService.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventRecruitDetail.java, src/main/java/com/barowoori/foodpinbackend/event/controller/EventController.java, src/main/java/com/barowoori/foodpinbackend/member/command/application/dto/CommonMember.java, src/main/java/com/barowoori/foodpinbackend/member/command/application/dto/RequestMember.java, src/main/java/com/barowoori/foodpinbackend/member/controller/MemberController.java, src/main/java/com/barowoori/foodpinbackend/truck/command/application/dto/RequestTruck.java, src/main/java/com/barowoori/foodpinbackend/truck/controller/TruckController.java
> #73 
> NotNull, NotEmpty validation 정상 작동하도록 전체 수정
> EventRecruitDto에 isRecruitEndOnSelection 추가, 생성 및 수정 시 포함되도록 수정
> 전체 참여 필수인 행사 지원 시, 행사의 전체 eventDate에 대해 자동으로 지원하도록 변경
=> ✨ isRecruitEndOnSelection added to EventRecruitDto.

src/main/java/com/barowoori/foodpinbackend/notification/command/application/service/TruckNotificationEventHandler.java, src/main/java/com/barowoori/foodpinbackend/pushAlarmHistory/command/application/dto/ResponsePushAlarmHistory.java
> ex) #87
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> :sparkles: push alarm target updated

src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/RecruitInfo.java, src/main/java/com/barowoori/foodpinbackend/event/command/domain/repository/dto/TruckEventApplicationList.java
> ex) #87
> 행사 목록에 선정시 마감 추가
>
=> :sparkles: event list updated

src/main/java/com/barowoori/foodpinbackend/config/security/SecurityConfig.java, src/main/java/com/barowoori/foodpinbackend/member/command/domain/model/SocialLoginInfo.java
> #130 
> 필터체인 예외 목록 v2 로그인 api 추가
=> ✨ v2 login api permitted without token.

src/main/java/com/barowoori/foodpinbackend/member/command/application/service/MemberService.java, src/main/java/com/barowoori/foodpinbackend/member/command/domain/repository/MemberRepository.java
> #130 
> 소셜 정보 조회 시 사용 jpa 쿼리 변경
=> ✨ find by social query changed.

src/main/java/com/barowoori/foodpinbackend/member/command/application/service/AuthCodeExchanger.java
=> ✨ logging added to code exchanger.

src/main/java/com/barowoori/foodpinbackend/event/command/application/service/EventService.java, src/main/java/com/barowoori/foodpinbackend/notification/command/application/service/TruckNotificationEventHandler.java, src/main/java/com/barowoori/foodpinbackend/notification/command/domain/model/truck/TruckSelectionConfirmedNotificationEvent.java
=> :sparkles: TRUCK_SELECTION_CONFIRMED alarm updated

src/main/java/com/barowoori/foodpinbackend/event/command/application/service/EventManagementService.java, src/main/java/com/barowoori/foodpinbackend/notification/command/application/service/EventNotificationEventHandler.java, src/main/java/com/barowoori/foodpinbackend/notification/command/application/service/TruckNotificationEventHandler.java, src/main/java/com/barowoori/foodpinbackend/notification/command/domain/model/truck/SelectionCompletedNotificationEvent.java
=> :sparkles: pushAlarm targetId updated

.github/workflows/cd.yml
> Docker image prune added to cd workflow.
=> ✨ Docker image prune added to cd workflow.

src/main/java/com/barowoori/foodpinbackend/event/command/domain/model/EventRecruitDetail.java
=> ⚡ EventRecruitDetail selectedCount logic fixed.

src/main/java/com/barowoori/foodpinbackend/event/command/application/service/EventService.java, src/main/java/com/barowoori/foodpinbackend/notification/command/application/service/TruckNotificationEventHandler.java, src/main/java/com/barowoori/foodpinbackend/notification/command/domain/model/truck/EventCastedNotificationEvent.java
=> :sparkles: event casted push alarm updated

Dockerfile
=> :sparkles: timezone setting

src/main/java/com/barowoori/foodpinbackend/config/logging/RestControllerLoggingAspect.java, src/main/java/com/barowoori/foodpinbackend/notification/command/application/service/TruckNotificationEventHandler.java, src/main/java/com/barowoori/foodpinbackend/notification/command/domain/model/truck/ManagerRemovedNotificationEvent.java, src/main/java/com/barowoori/foodpinbackend/truck/command/application/service/TruckService.java
=> :sparkles: dto log added
